- name: loops package
  hosts: web
  become: yes
  connection: local
  tasks: 
  - name: install packages
    ansible.builtin.package:
      name: " {{ item }}" #item is reserved keyword
      state: present
    loop:
    - mysql
    - nginx
    - postfix
    - httpd