- name: demo on functions
  hosts: local
  connection: local
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('Ansible') }}"

  - name: convert upper case
    vars:
      greeting: "Hello nagendra"  
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"  


  - name: convert lower case
    vars:
      greeting: "Hello nagendra"  
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"