- name: create ec2 and r5 records
  hosts: local
  connection: local
  vars: 
    subnet_id: subnet-08d3347d6290ba403
    sg_id: sg-0a0126e56d52ad4e9
    ami_id: ami-09c813fb71547fc4f
    instances:
    - mysql
    - backend
    - frontend
    zone: daws81.space
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
      loop: "{{ instances }}"
      register: ec2_instances

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ ec2_instances }}"  

    #private IP R53
    - name: create r53 private records
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"    #mysql.daws81.space
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"


    #public IP R53
    - name: create r53 public records for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ zone }}"
        record: "{{ item.item }}.{{ zone }}"    #frontend.daws81.space
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"
      when: item.item == "frontend"